language: bash

sudo: required

os:
    - linux
    - osx

install:
    -  ./shell-ci-build/install.sh

before_script:
    - curl -L "http://downloads.sourceforge.net/shunit2/shunit2-2.0.3.tgz" | tar zx
    - chmod +x $(pwd)/shunit2-2.0.3/src/shell/shunit2

script:
    - export SHUNIT2=$(pwd)/shunit2-2.0.3/src/shell/shunit2
    - make test
    - ./shell-ci-build.sh
